const types = {
  GET_ALL_TAGS_REQUEST: "GET_ALL_TAGS_REQUEST",
  GET_ALL_TAGS_SUCCESS: "GET_ALL_TAGS_SUCCESS",
  GET_ALL_TAGS_ERROR: "GET_ALL_TAGS_ERROR",

  GET_PROBLEMS_BY_TAGS_REQUEST: "GET_PROBLEMS_BY_TAGS_REQUEST",
  GET_PROBLEMS_BY_TAGS_SUCCESS: "GET_PROBLEMS_BY_TAGS_SUCCESS",
  GET_PROBLEMS_BY_TAGS_ERROR: "GET_PROBLEMS_BY_TAGS_ERROR",

  CREATE_PROBLEM_REQUEST: "CREATE_PROBLEM_REQUEST",
  CREATE_PROBLEM_SUCCESS: "CREATE_PROBLEM_SUCCESS",
  CREATE_PROBLEM_ERROR: "CREATE_PROBLEM_ERROR",

  EDIT_PROBLEM_REQUEST: "EDIT_PROBLEM_REQUEST",
  EDIT_PROBLEM_SUCCESS: "EDIT_PROBLEM_SUCCESS",
  EDIT_PROBLEM_ERROR: "EDIT_PROBLEM_ERROR",

  CREATE_TAG_REQUEST: "CREATE_TAG_REQUEST",
  CREATE_TAG_SUCCESS: "CREATE_TAG_SUCCESS",
  CREATE_TAG_ERROR: "CREATE_TAG_ERROR",

  EMPTY_STATE_AFTER_LOGOUT: "EMPTY_STATE_AFTER_LOGOUT",
};
export default types;
