const types = {
  // sendResetPasswordLink
  RESET_PASSWORD_LINK_REQUEST: "RESET_PASSWORD_LINK_REQUEST",
  RESET_PASSWORD_LINK_SUCCESS: "RESET_PASSWORD_LINK_SUCCESS",
  RESET_PASSWORD_LINK_ERROR: "RESET_PASSWORD_LINK_ERROR",
};
export default types;
